In [9]:
import numpy as np
import logging
from tensorflow.keras.models import load_model

# Set up logging to both console and file
log_filename = 'prediction_logs.txt'
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_filename),  # Log to a file
        logging.StreamHandler()              # Log to console
    ]
)

# Load preprocessed test data
def load_test_data():
    logging.info("Loading test data...")
    input_sequences_test = np.load('input_sequences_test.npy')
    next_step_targets_test = np.load('next_step_targets_test.npy')
    logging.info("Test data loaded successfully.")
    return input_sequences_test, next_step_targets_test

# Load the trained models
def load_models_mae():
    logging.info("Loading MAE models...")
    lstm_model = load_model('lstm_model_mae.keras')
    gru_model = load_model('gru_model_mae.keras')
    logging.info("MAE models loaded successfully.")
    return lstm_model, gru_model

def load_models_rmse():
    logging.info("Loading RMSE models...")
    lstm_model = load_model('lstm_model_rmse.keras')
    gru_model = load_model('gru_model_rmse.keras')
    logging.info("RMSE models loaded successfully.")
    return lstm_model, gru_model

# Make predictions using the LSTM and GRU models
def make_predictions_mae(input_sequences_test, lstm_model_mae, gru_model_mae):
    logging.info("Making predictions using MAE models...")
    lstm_predictions_mae = lstm_model_mae.predict(input_sequences_test)
    gru_predictions_mae = gru_model_mae.predict(input_sequences_test)
    logging.info("Predictions made successfully using MAE models.")
    return lstm_predictions_mae, gru_predictions_mae

def make_predictions_rmse(input_sequences_test, lstm_model_rmse, gru_model_rmse):
    logging.info("Making predictions using RMSE models...")
    lstm_predictions_rmse = lstm_model_rmse.predict(input_sequences_test)
    gru_predictions_rmse = gru_model_rmse.predict(input_sequences_test)
    logging.info("Predictions made successfully using RMSE models.")
    return lstm_predictions_rmse, gru_predictions_rmse

# Save predictions to a text file
def save_predictions_to_file(lstm_predictions_mae, gru_predictions_mae, lstm_predictions_rmse, gru_predictions_rmse):
    with open('predictions.txt', 'w') as f:
        f.write("LSTM Predictions for MAE:\n")
        f.write(np.array2string(lstm_predictions_mae, precision=4))
        f.write("\n\nGRU Predictions for MAE:\n")
        f.write(np.array2string(gru_predictions_mae, precision=4))
        f.write("\n\nLSTM Predictions for RMSE:\n")
        f.write(np.array2string(lstm_predictions_rmse, precision=4))
        f.write("\n\nGRU Predictions for RMSE:\n")
        f.write(np.array2string(gru_predictions_rmse, precision=4))
    logging.info("Predictions saved to predictions.txt")

# Example usage for making predictions
if __name__ == "__main__":
    input_sequences_test, next_step_targets_test = load_test_data()
    
    lstm_model_mae, gru_model_mae = load_models_mae()
    lstm_predictions_mae, gru_predictions_mae = make_predictions_mae(input_sequences_test, lstm_model_mae, gru_model_mae)

    lstm_model_rmse, gru_model_rmse = load_models_rmse()
    lstm_predictions_rmse, gru_predictions_rmse = make_predictions_rmse(input_sequences_test, lstm_model_rmse, gru_model_rmse)

    # Log predictions
    logging.info(f"LSTM Predictions for MAE: {lstm_predictions_mae}")
    logging.info(f"GRU Predictions for MAE: {gru_predictions_mae}")
    logging.info(f"LSTM Predictions for RMSE: {lstm_predictions_rmse}")
    logging.info(f"GRU Predictions for RMSE: {gru_predictions_rmse}")

    # Print predictions to console
    print("LSTM Predictions for MAE: ", lstm_predictions_mae)
    print("GRU Predictions for MAE: ", gru_predictions_mae)
    print("LSTM Predictions for RMSE: ", lstm_predictions_rmse)
    print("GRU Predictions for RMSE: ", gru_predictions_rmse)

    # Save predictions to a file
    save_predictions_to_file(lstm_predictions_mae, gru_predictions_mae, lstm_predictions_rmse, gru_predictions_rmse)


2024-10-02 01:30:31,617 - INFO - Loading test data...
2024-10-02 01:30:31,665 - INFO - Test data loaded successfully.
2024-10-02 01:30:31,672 - INFO - Loading MAE models...
2024-10-02 01:30:31,812 - INFO - MAE models loaded successfully.
2024-10-02 01:30:31,813 - INFO - Making predictions using MAE models...


214/214 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
214/214 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


2024-10-02 01:30:34,204 - INFO - Predictions made successfully using MAE models.
2024-10-02 01:30:34,206 - INFO - Loading RMSE models...
2024-10-02 01:30:34,322 - INFO - RMSE models loaded successfully.
2024-10-02 01:30:34,324 - INFO - Making predictions using RMSE models...


214/214 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
214/214 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


2024-10-02 01:30:36,661 - INFO - Predictions made successfully using RMSE models.
2024-10-02 01:30:36,663 - INFO - LSTM Predictions for MAE: [[0.9200382  0.9048626  0.9380377  ... 0.90774155 0.9484708  0.8971268 ]
 [0.9245748  0.9036465  0.9335128  ... 0.9096299  0.9453987  0.8908576 ]
 [0.92648244 0.9093925  0.93441063 ... 0.91226226 0.9502695  0.89856136]
 ...
 [0.8264682  0.9083483  0.95791936 ... 0.9005002  0.96925163 0.8640795 ]
 [0.8439106  0.9090371  0.9568298  ... 0.892611   0.9645843  0.8758998 ]
 [0.8054622  0.90837604 0.95892876 ... 0.8989943  0.9647614  0.87870526]]
2024-10-02 01:30:36,664 - INFO - GRU Predictions for MAE: [[0.95649326 0.933741   0.96280503 ... 0.8926368  0.9835138  0.89726126]
 [0.95355785 0.93389827 0.96204555 ... 0.8877131  0.9838147  0.89753133]
 [0.95484537 0.93544424 0.9642203  ... 0.8951805  0.9849668  0.9001266 ]
 ...
 [0.92824364 0.94424075 0.9712984  ... 0.91643196 0.98912674 0.87554777]
 [0.9396087  0.9450698  0.972717   ... 0.9198737  0.98775536

LSTM Predictions for MAE:  [[0.9200382  0.9048626  0.9380377  ... 0.90774155 0.9484708  0.8971268 ]
 [0.9245748  0.9036465  0.9335128  ... 0.9096299  0.9453987  0.8908576 ]
 [0.92648244 0.9093925  0.93441063 ... 0.91226226 0.9502695  0.89856136]
 ...
 [0.8264682  0.9083483  0.95791936 ... 0.9005002  0.96925163 0.8640795 ]
 [0.8439106  0.9090371  0.9568298  ... 0.892611   0.9645843  0.8758998 ]
 [0.8054622  0.90837604 0.95892876 ... 0.8989943  0.9647614  0.87870526]]
GRU Predictions for MAE:  [[0.95649326 0.933741   0.96280503 ... 0.8926368  0.9835138  0.89726126]
 [0.95355785 0.93389827 0.96204555 ... 0.8877131  0.9838147  0.89753133]
 [0.95484537 0.93544424 0.9642203  ... 0.8951805  0.9849668  0.9001266 ]
 ...
 [0.92824364 0.94424075 0.9712984  ... 0.91643196 0.98912674 0.87554777]
 [0.9396087  0.9450698  0.972717   ... 0.9198737  0.98775536 0.8957355 ]
 [0.92972505 0.94752824 0.973199   ... 0.9184186  0.9897701  0.8854579 ]]
LSTM Predictions for RMSE:  [[0.9680094  0.913039   0.94901